### ISSUE TITLE
Invalid normalized page paths

### ISSUE THREAD

**Issue by hissy** [concrete5/addon_migration_tool#5]
`NormalizePagePathsTask#finish` makes invalid page paths.

Example:

Original paths

* /2015/foo
* /2014/bar

Batch paths

* 15/foo
* 14/bar

**Comment by aembler** [comment]
Yeah, this is definitely a bug. it should be /2015/foo and /2014/bar. Basically, only if a complete path segment exists should it be cut off. 

I've added these two test examples to the processor test that we have in there. It's currently failing – but if we could fix it so that it would succeed that would be awesome.

**Comment by hissy** [comment]
Tests bundled in this repository does not work. Could you write some into README file?

**Comment by aembler** [comment]
I'm not sure I understand. The tests are supposed to be failing because this is indeed a bug. We need to fix the code that causes the test to fail.

The tests aren't dying – but they are failing.

...F.

Time: 277 ms, Memory: 20.00Mb

There was 1 failure:

1) ProcessingTest::testLinkNormalizationYear
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/2014/foo'
+'4/foo'

/Users/andrewembler/git/addon_migration_tool/tests/tests/Parser/ProcessingTest.php:57
