### ISSUE TITLE
Error during import process

### ISSUE THREAD

**Issue by serincharnley** [concrete5/addon_migration_tool#54]
We are having an issue during the import process. The following is the error in the concrete5 logs. 
 
Exception Occurred: /home/phoenix/public_html/c58/packages/migration_tool/src/PortlandLabs/Concrete5/MigrationTool/Batch/Validator/Page/Content/FileItemValidator.php:31 Call to undefined method Concrete\Core\Backup\ContentImporter\ValueInspector\Item\FileItem::getPrefix() (1)

After uploading the xml file, it says under pages: Load error! (Internal Server Error)
For Status it just thinks and says: Computing Batch Status

We have used the same add-on on another site and it works fine, the C58 Version is 8.3.2. The version of the problem site is 8.2.1, but this Migration Tool says that version is included.

We checked the file size, and that's not it, as we are just doing a few test pages. We tried to clear the cache as well, and no change.

**Comment by aembler** [comment]
My apologies – it looks like we should have updated the required version at the point where we added this code. In 8.3.1 we add a prefix field to the files, which makes it possible to map existing files rather than constantly reimport them into migrated sites. But this does require that the site we're importing into run 8.3.1 or greater. I have updated the controller.php requirements.
